### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by p3lim** [vetletm/hacking-portal#23]
- [x] OpenStack integration
   - [x] API handlers
- [ ] Session @ database
- [x] Student names from LDAP @p3lim 
- [x] Machine IPs from OpenStack @vetletm 
- [x] metalinting @p3lim
- [x] Tests
   - [x] routes
   - [x] database
- [x] Readmes
   - [x] Repo
   - [x] Build
- [x] Test deployment
- [x] Get peer reviewed
